/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as PropertiesSubscriptionRouteImport } from './routes/properties/subscription'
import { Route as PropertiesSettingsRouteImport } from './routes/properties/settings'
import { Route as PropertiesHelpRouteImport } from './routes/properties/help'
import { Route as PropertiesAddRouteImport } from './routes/properties/add'
import { Route as DashboardTenantsRouteImport } from './routes/dashboard/tenants'
import { Route as DashboardSecuritydepositsRouteImport } from './routes/dashboard/securitydeposits'
import { Route as DashboardRepairsRouteImport } from './routes/dashboard/repairs'
import { Route as DashboardRenttrackingRouteImport } from './routes/dashboard/renttracking'
import { Route as DashboardInspectionsRouteImport } from './routes/dashboard/inspections'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home'
import { Route as DashboardExpensesRouteImport } from './routes/dashboard/expenses'
import { Route as DashboardAgreementRouteImport } from './routes/dashboard/agreement'
import { Route as DashboardAdvertiseRouteImport } from './routes/dashboard/advertise'
import { Route as authVerifyRouteImport } from './routes/(auth)/verify'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authPinRouteImport } from './routes/(auth)/pin'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as PropertiesPropertyIdEditRouteImport } from './routes/properties/$propertyId.edit'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSubscriptionRoute = PropertiesSubscriptionRouteImport.update({
  id: '/properties/subscription',
  path: '/properties/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSettingsRoute = PropertiesSettingsRouteImport.update({
  id: '/properties/settings',
  path: '/properties/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesHelpRoute = PropertiesHelpRouteImport.update({
  id: '/properties/help',
  path: '/properties/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesAddRoute = PropertiesAddRouteImport.update({
  id: '/properties/add',
  path: '/properties/add',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTenantsRoute = DashboardTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSecuritydepositsRoute =
  DashboardSecuritydepositsRouteImport.update({
    id: '/securitydeposits',
    path: '/securitydeposits',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardRepairsRoute = DashboardRepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRenttrackingRoute = DashboardRenttrackingRouteImport.update({
  id: '/renttracking',
  path: '/renttracking',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInspectionsRoute = DashboardInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExpensesRoute = DashboardExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgreementRoute = DashboardAgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdvertiseRoute = DashboardAdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authVerifyRoute = authVerifyRouteImport.update({
  id: '/(auth)/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authPinRoute = authPinRouteImport.update({
  id: '/(auth)/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesPropertyIdEditRoute =
  PropertiesPropertyIdEditRouteImport.update({
    id: '/properties/$propertyId/edit',
    path: '/properties/$propertyId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/pin': typeof authPinRoute
  '/register': typeof authRegisterRoute
  '/verify': typeof authVerifyRoute
  '/dashboard/advertise': typeof DashboardAdvertiseRoute
  '/dashboard/agreement': typeof DashboardAgreementRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/inspections': typeof DashboardInspectionsRoute
  '/dashboard/renttracking': typeof DashboardRenttrackingRoute
  '/dashboard/repairs': typeof DashboardRepairsRoute
  '/dashboard/securitydeposits': typeof DashboardSecuritydepositsRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/properties/add': typeof PropertiesAddRoute
  '/properties/help': typeof PropertiesHelpRoute
  '/properties/settings': typeof PropertiesSettingsRoute
  '/properties/subscription': typeof PropertiesSubscriptionRoute
  '/': typeof authIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/properties/$propertyId/edit': typeof PropertiesPropertyIdEditRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/pin': typeof authPinRoute
  '/register': typeof authRegisterRoute
  '/verify': typeof authVerifyRoute
  '/dashboard/advertise': typeof DashboardAdvertiseRoute
  '/dashboard/agreement': typeof DashboardAgreementRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/inspections': typeof DashboardInspectionsRoute
  '/dashboard/renttracking': typeof DashboardRenttrackingRoute
  '/dashboard/repairs': typeof DashboardRepairsRoute
  '/dashboard/securitydeposits': typeof DashboardSecuritydepositsRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/properties/add': typeof PropertiesAddRoute
  '/properties/help': typeof PropertiesHelpRoute
  '/properties/settings': typeof PropertiesSettingsRoute
  '/properties/subscription': typeof PropertiesSubscriptionRoute
  '/': typeof authIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/properties/$propertyId/edit': typeof PropertiesPropertyIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/pin': typeof authPinRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/verify': typeof authVerifyRoute
  '/dashboard/advertise': typeof DashboardAdvertiseRoute
  '/dashboard/agreement': typeof DashboardAgreementRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/inspections': typeof DashboardInspectionsRoute
  '/dashboard/renttracking': typeof DashboardRenttrackingRoute
  '/dashboard/repairs': typeof DashboardRepairsRoute
  '/dashboard/securitydeposits': typeof DashboardSecuritydepositsRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/properties/add': typeof PropertiesAddRoute
  '/properties/help': typeof PropertiesHelpRoute
  '/properties/settings': typeof PropertiesSettingsRoute
  '/properties/subscription': typeof PropertiesSubscriptionRoute
  '/(auth)/': typeof authIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/properties/$propertyId/edit': typeof PropertiesPropertyIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/login'
    | '/pin'
    | '/register'
    | '/verify'
    | '/dashboard/advertise'
    | '/dashboard/agreement'
    | '/dashboard/expenses'
    | '/dashboard/home'
    | '/dashboard/inspections'
    | '/dashboard/renttracking'
    | '/dashboard/repairs'
    | '/dashboard/securitydeposits'
    | '/dashboard/tenants'
    | '/properties/add'
    | '/properties/help'
    | '/properties/settings'
    | '/properties/subscription'
    | '/'
    | '/properties/'
    | '/properties/$propertyId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/login'
    | '/pin'
    | '/register'
    | '/verify'
    | '/dashboard/advertise'
    | '/dashboard/agreement'
    | '/dashboard/expenses'
    | '/dashboard/home'
    | '/dashboard/inspections'
    | '/dashboard/renttracking'
    | '/dashboard/repairs'
    | '/dashboard/securitydeposits'
    | '/dashboard/tenants'
    | '/properties/add'
    | '/properties/help'
    | '/properties/settings'
    | '/properties/subscription'
    | '/'
    | '/properties'
    | '/properties/$propertyId/edit'
  id:
    | '__root__'
    | '/dashboard'
    | '/(auth)/login'
    | '/(auth)/pin'
    | '/(auth)/register'
    | '/(auth)/verify'
    | '/dashboard/advertise'
    | '/dashboard/agreement'
    | '/dashboard/expenses'
    | '/dashboard/home'
    | '/dashboard/inspections'
    | '/dashboard/renttracking'
    | '/dashboard/repairs'
    | '/dashboard/securitydeposits'
    | '/dashboard/tenants'
    | '/properties/add'
    | '/properties/help'
    | '/properties/settings'
    | '/properties/subscription'
    | '/(auth)/'
    | '/properties/'
    | '/properties/$propertyId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authPinRoute: typeof authPinRoute
  authRegisterRoute: typeof authRegisterRoute
  authVerifyRoute: typeof authVerifyRoute
  PropertiesAddRoute: typeof PropertiesAddRoute
  PropertiesHelpRoute: typeof PropertiesHelpRoute
  PropertiesSettingsRoute: typeof PropertiesSettingsRoute
  PropertiesSubscriptionRoute: typeof PropertiesSubscriptionRoute
  authIndexRoute: typeof authIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  PropertiesPropertyIdEditRoute: typeof PropertiesPropertyIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/subscription': {
      id: '/properties/subscription'
      path: '/properties/subscription'
      fullPath: '/properties/subscription'
      preLoaderRoute: typeof PropertiesSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/settings': {
      id: '/properties/settings'
      path: '/properties/settings'
      fullPath: '/properties/settings'
      preLoaderRoute: typeof PropertiesSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/help': {
      id: '/properties/help'
      path: '/properties/help'
      fullPath: '/properties/help'
      preLoaderRoute: typeof PropertiesHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/add': {
      id: '/properties/add'
      path: '/properties/add'
      fullPath: '/properties/add'
      preLoaderRoute: typeof PropertiesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tenants': {
      id: '/dashboard/tenants'
      path: '/tenants'
      fullPath: '/dashboard/tenants'
      preLoaderRoute: typeof DashboardTenantsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/securitydeposits': {
      id: '/dashboard/securitydeposits'
      path: '/securitydeposits'
      fullPath: '/dashboard/securitydeposits'
      preLoaderRoute: typeof DashboardSecuritydepositsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/repairs': {
      id: '/dashboard/repairs'
      path: '/repairs'
      fullPath: '/dashboard/repairs'
      preLoaderRoute: typeof DashboardRepairsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/renttracking': {
      id: '/dashboard/renttracking'
      path: '/renttracking'
      fullPath: '/dashboard/renttracking'
      preLoaderRoute: typeof DashboardRenttrackingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inspections': {
      id: '/dashboard/inspections'
      path: '/inspections'
      fullPath: '/dashboard/inspections'
      preLoaderRoute: typeof DashboardInspectionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/expenses': {
      id: '/dashboard/expenses'
      path: '/expenses'
      fullPath: '/dashboard/expenses'
      preLoaderRoute: typeof DashboardExpensesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/agreement': {
      id: '/dashboard/agreement'
      path: '/agreement'
      fullPath: '/dashboard/agreement'
      preLoaderRoute: typeof DashboardAgreementRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/advertise': {
      id: '/dashboard/advertise'
      path: '/advertise'
      fullPath: '/dashboard/advertise'
      preLoaderRoute: typeof DashboardAdvertiseRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/verify': {
      id: '/(auth)/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof authVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/pin': {
      id: '/(auth)/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof authPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$propertyId/edit': {
      id: '/properties/$propertyId/edit'
      path: '/properties/$propertyId/edit'
      fullPath: '/properties/$propertyId/edit'
      preLoaderRoute: typeof PropertiesPropertyIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAdvertiseRoute: typeof DashboardAdvertiseRoute
  DashboardAgreementRoute: typeof DashboardAgreementRoute
  DashboardExpensesRoute: typeof DashboardExpensesRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardInspectionsRoute: typeof DashboardInspectionsRoute
  DashboardRenttrackingRoute: typeof DashboardRenttrackingRoute
  DashboardRepairsRoute: typeof DashboardRepairsRoute
  DashboardSecuritydepositsRoute: typeof DashboardSecuritydepositsRoute
  DashboardTenantsRoute: typeof DashboardTenantsRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdvertiseRoute: DashboardAdvertiseRoute,
  DashboardAgreementRoute: DashboardAgreementRoute,
  DashboardExpensesRoute: DashboardExpensesRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardInspectionsRoute: DashboardInspectionsRoute,
  DashboardRenttrackingRoute: DashboardRenttrackingRoute,
  DashboardRepairsRoute: DashboardRepairsRoute,
  DashboardSecuritydepositsRoute: DashboardSecuritydepositsRoute,
  DashboardTenantsRoute: DashboardTenantsRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authPinRoute: authPinRoute,
  authRegisterRoute: authRegisterRoute,
  authVerifyRoute: authVerifyRoute,
  PropertiesAddRoute: PropertiesAddRoute,
  PropertiesHelpRoute: PropertiesHelpRoute,
  PropertiesSettingsRoute: PropertiesSettingsRoute,
  PropertiesSubscriptionRoute: PropertiesSubscriptionRoute,
  authIndexRoute: authIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  PropertiesPropertyIdEditRoute: PropertiesPropertyIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
